# Prometheus configuration for SentinelAI
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

scrape_configs:
  # SentinelAI metrics
  - job_name: 'sentinelai'
    static_configs:
      - targets: ['sentinelai:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  # Grafana metrics (optional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

  # Node exporter for system metrics (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s